name: Money_Control_Scrap

on:
  push:
    branches:
      - src  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'  # specify the Python version you're using
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt

    - name: Build package
      run: |
        python -m build

    - name: Package and deploy
      with: 
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload --skip-existing dist/*
