name: Python Package

on:
  push:
    branches:
      - src  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'  # specify the Python version you're using
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests  # Add your test commands here if you have tests
      run: |
        pip install pytest pytest-cov
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Package and deploy
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload --skip-existing dist/*
